apiVersion: v1
kind: Service
metadata:
  name: simple-webserver
  labels:
    app: simple-webserver
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8082
  selector:
    app: simple-webserver
    tier: frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simple-webserver
  labels:
    app: simple-webserver
spec:
  template:
    metadata:
      labels:
        app: simple-webserver
        tier: frontend
    spec:
      containers:
      - image: andygrunwald/simple-webserver:v1.1.1
        name: simple-webserver
        command: ["app", "-redis", "simple-webserver-redis:6379"]
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: simple-webserver-redis
  labels:
    app: simple-webserver
spec:
  ports:
    - port: 6379
  selector:
    app: simple-webserver
    tier: redis
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simple-webserver-redis
  labels:
    app: simple-webserver
spec:
  template:
    metadata:
      labels:
        app: simple-webserver
        tier: redis
    spec:
      containers:
      - image: redis:3-alpine
        name: redis
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: simple-webserver
  name: simple-webserver
  namespace: default
spec:
  backend:
    serviceName: simple-webserver
    servicePort: 8082
